hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}

data_dir: /home/user/work/CMI2024/data/child-mind-institute-problematic-internet-use
output_dir: /home/user/work/CMI2024/CMI2-Pipeline/results/${exp_name}
oof_path:

# "CustomLGBMRegressor" or "CustomXGBRegressor" or "CustomLGBMClassifier" or "CustomXGBClassifier"
model_name: CustomXGBClassifier
exp_name: exp87

